services:
  # Backend Service
  - type: web
    name: tourism-backend
    env: python
    rootDirectory: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        generateValue: true

  # Frontend Service
  - type: static
    name: tourism-frontend
    rootDirectory: frontend
    buildCommand: "pnpm install && pnpm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: tourism-backend
          property: host

databases:
  - name: tourism-db
    databaseName: tourism_platform
    user: tourism_user

